//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES
    {
        public int ID { get; set; }
        public string SERIALSENSOR { get; set; }
        public double MEDICION { get; set; }
        public double LATITUD { get; set; }
        public double LONGITUD { get; set; }
        public System.DateTime DATEREPORTED { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime DATELASTMODIFICATION { get; set; }
    }
}
