//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENSORES
    {
        public int ID { get; set; }
        public string SERIAL { get; set; }
        public string PASSWORD { get; set; }
        public string TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime DATECREATED { get; set; }
        public System.DateTime DATELASTMODIFICATION { get; set; }
    }
}
