//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorDevice
    {
        public int ID_REG { get; set; }
        public int ID_SENSOR { get; set; }
        public double MEDICION { get; set; }
        public System.DateTime FECHAYHORA { get; set; }
    }
}
