//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID { get; set; }
        public string ROL { get; set; }
        public string NOMBRE { get; set; }
        public string CORREO { get; set; }
        public string DOC_TYPE { get; set; }
        public string DOCUMENTO { get; set; }
        public string PASSWORD { get; set; }
    }
}
